[package]
name = "partitioning_into_minimum_number_of_deci_binary_numbers_1689"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
